version: '3'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql
    environment:
      - POSTGRES_DB=usbguard
      - POSTGRES_USER=alpha
      - POSTGRES_HOST_AUTH_METHOD=trust